### ISSUE TITLE
Broken Table In Prefab Page

### ISSUE THREAD

**Issue by Kuinox** [stride3d/stride-docs#100]
This page about prefabs display a broken markdown table:  
https://doc.stride3d.net/latest/en/manual/game-studio/prefabs/use-prefabs.html

**Comment by VaclavElias** [comment]
Thanks, I will fix it.

![image](https://user-images.githubusercontent.com/4528464/232163062-b1872b6f-82a0-42c4-a843-d986fe02941b.png)
