### ISSUE TITLE
chore: Remove and replace all references to Xenko in the documentation

### ISSUE THREAD

**Issue by Jklawreszuk** [stride3d/stride-docs#219]
The mention of Xenko may be confusing for new users and should be replaced with the current engine name. 
I'm creating this issue for tracking 😃

- [x] https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html
- [x] https://doc.stride3d.net/latest/en/manual/troubleshooting/stride-doesnt-run.html
- [x] https://doc.stride3d.net/latest/en/manual/stride-launcher/index.html
- [x] https://doc.stride3d.net/latest/en/manual/get-started/index.html
- [x] https://doc.stride3d.net/latest/en/manual/get-started/visual-studio-extension.html
- [x] https://doc.stride3d.net/latest/en/manual/get-started/launch-stride.html
- [x] https://doc.stride3d.net/latest/en/manual/get-started/create-a-project.html

Vaclav: There is lots of Xenko. The easy solution is just to replace the images with the current ones. Please make them **.webp**.

**Comment by VaclavElias** [comment]
Hi @ElvinPero. Thank you. I believe, @Jklawreszuk is referring to these 2 pages at least? Am I right?

There is lots of Xenko. The easy solution is just to replace the images with the current ones. Please make them `.webp`. 

More time conusiming would be to actually to review the processes and add any missing text content and screenshots but that can be actually a separate issue. 

https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html
https://doc.stride3d.net/latest/en/manual/stride-launcher/index.html

Do you want me to assing this issue to you?

**Comment by VaclavElias** [comment]
We found other 4 pages with the old Xenko screenshots..

https://doc.stride3d.net/latest/en/manual/get-started/index.html
https://doc.stride3d.net/latest/en/manual/get-started/visual-studio-extension.html
https://doc.stride3d.net/latest/en/manual/get-started/launch-stride.html
https://doc.stride3d.net/latest/en/manual/get-started/create-a-project.html

**Comment by VaclavElias** [comment]
I upadated the original description with a Task list.

**Comment by VaclavElias** [comment]
Yes, please, you can remove the steps that are no longer needed. We can always update the docs if something is missed.

Regarding the PRs, your call in this case, because these are **safe** updates so it doesn't matter if it is just one PR or multiple, whatever works for you 😁.

Thank you.

**Comment by VaclavElias** [comment]
Hi @ElvinPero, do you have any update for us?

**Comment by parhamgholami** [comment]
If this isn't an urgent task, I could take this on over the next two-ish weeks while I'm waiting for feedback to come in for the blog post.

**Comment by parhamgholami** [comment]
Sounds good! I'll post updates when I get started. 😄

**Comment by Kryptos-FR** [comment]
@parhamgholami I can take the first one (https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html), if you like. I already started collecting the screenshots.

**Comment by parhamgholami** [comment]
> @parhamgholami I can take the first one (https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html), if you like. I already started collecting the screenshots.

Sounds good!

**Comment by VaclavElias** [comment]
I have ticked the first box so `install-stride.md` is done.

**Comment by Kryptos-FR** [comment]
Adding https://doc.stride3d.net/latest/en/manual/troubleshooting/stride-doesnt-run.html to the list, since it is referenced by the Getting Started page.

**Comment by parhamgholami** [comment]
Just wanted to give an update: I haven't started on this yet. Now that I finished the blog post, I'll be focusing on this next. Should be starting as soon as tomorrow or Sunday.

**Comment by minktusk** [comment]
Can i be assign?

I have already update some screenshots on the Get started!

However, i din't update yet screenshots in the Assets and Scenes tabs!

https://github.com/user-attachments/assets/d24e8c13-426d-4e18-b67c-f1f0d6406eb9

**Comment by VaclavElias** [comment]
@parhamgholami, I will be assigning also @minktusk. I hope it is ok :)

**Comment by VaclavElias** [comment]
@minktusk, yes please.

**Comment by VaclavElias** [comment]
@minktusk, do you have any update for us? 🙂

**Comment by VaclavElias** [comment]
@minktusk, I think we can close this. If there are other pages which you mentioned, we shall open a new issue. What do you think?

**Comment by minktusk** [comment]
> [@minktusk](https://github.com/minktusk), I think we can close this. If there are other pages which you mentioned, we shall open a new issue. What do you think?

Sure!

**Comment by VaclavElias** [comment]
This issue is now resolved.
