### ISSUE TITLE
Can I add Chinese here? a new language!

### ISSUE THREAD

**Issue by Arc-huangjingtong** [stride3d/stride-docs#305]
China has a huge mobile game market,because of the unity event , more and more people need to understand this elegant engine, This may attract more game developers.

**Comment by VaclavElias** [comment]
Hi @Arc-huangjingtong. Thank you for your interest in adding a Chinese translation. 

Adding a new language requires a significant amount of work. It's not just about translating the existing documentation; it also involves maintaining it. Every time we update the English documentation, the changes need to be reflected in the translated versions as well. This means continuous updates and checks to ensure all versions are synchronized.

Maintaining the documentation in multiple languages is a complex and ongoing effort. It requires a dedicated team of translators and maintainers who can keep the non-English docs up-to-date with the latest changes.

Are you aware of more Chinese-speaking developers who could help with maintaining the docs? A community effort would make this much more feasible. I know there are many!🙂

Let's keep this conversation open, as I need to make some adjustments to our docs generation script to better support multiple languages. Also, we can track people willing to help with the translation.

Also, could you clarify your intention? Are you looking to translate individual pages or just the navigation menus to start with?

Thank you again for your enthusiasm and support! 😊

**Comment by Arc-huangjingtong** [comment]
Thank you! I want to know the inclusiveness of the stride team. I will need to take time to prepare.

the clarify is : i want translate all the page in Learn manual

**Comment by Arc-huangjingtong** [comment]
I can know that the stride team is willing to accept Chinese, so I can prepare with confidence.

**Comment by IXLLEGACYIXL** [comment]
> Thank you! I want to know the inclusiveness of the stride team. I will need to take time to prepare.
> 
> the clarify is : i want translate all the page in Learn manual

everything, everyone is included, its just about resources

the japanese docs are existing but it is halted as nobody is maintaining it

**Comment by VaclavElias** [comment]
Yes, the Stride team is open to any language 🙂. However, we are concerned about translated docs becoming outdated if they are abandoned. Ideally, there should be at least 2-3 community members supporting each language to ensure it stays updated with future versions. If there are no language maintainers, we might just remove the language.

**Comment by Arc-huangjingtong** [comment]
thank you , I understand that this is a difficult choice, and I will consider this matter carefully.

**Comment by VaclavElias** [comment]
You are welcome. 

If anyone else would like to help with the Chinese translation, please let us know.
