### ISSUE TITLE
API reference class pages should show inherited members

### ISSUE THREAD

**Issue by jeske** [stride3d/stride-docs#33]
(this is a tracking issue for myself... im working on it right now)

_Why?_ 

Right now the class pages are very hard to use, because they don't show any of the inherited members. It is pretty standard for API pages to show (most) inherited members, so understanding a class API does not require clicking and paging and control-F searching through 5+ different superclass pages. 
For example, the Button docs page...

https://doc.xenko.com/latest/en/api/Stride.UI.Controls.Button.html

Does not have the `Click` event, because it's inherited from ButtonBase. Which makes it a bit of a confusing mess to figure out how to do the simple task of handling a click. For comparison, see [Unity UI.Button](https://docs.unity3d.com/530/Documentation/ScriptReference/UI.Button.html), or [Microsoft S.W.F.Button](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.button?view=netcore-3.1)

**Comment by VaclavElias** [comment]
I believe, the new DocFX does the job as you can see in the screen shot.

<img width="941" alt="image" src="https://github.com/stride3d/stride-docs/assets/4528464/25e9d6d9-cd72-4cc9-b9db-828cf5aed434">

Closing this issue as resolved.
