### ISSUE TITLE
some derived class trees have busted visuals

### ISSUE THREAD

**Issue by jeske** [stride3d/stride-docs#34]
(im working on this, this issue is a tracking issue)

The docs pages show an inheritence tree which places the currently viewed class in context.. with superclasses above, and derived classes below. This is a *correctly* displayed tree example:

![image](https://user-images.githubusercontent.com/15093/81247862-ea4ae300-8fcf-11ea-9339-8e6c398971cb.png)

For some reason, sometimes this tree gets broken, and derived classes are not displayed correctly. This is an *incorrect* display. 

![image](https://user-images.githubusercontent.com/15093/81247918-09e20b80-8fd0-11ea-9f5a-d53a1c1b8909.png)

The link for the derived class `ImageButton` should be properly indented, and prefaced by the inheritance arrow, like derived classes are in the correct example above.

**Comment by VaclavElias** [comment]
The new DocFX doesn't have this functionality so the new Stride Docs doesn't utilise this anymore.

Closing this issue as resolved.
