### ISSUE TITLE
Add a .gitignore example to the version control section

### ISSUE THREAD

**Issue by grandslammer** [stride3d/stride-docs#47]
Just something that a user can copy and paste into their own .gitignore to get started using the standard recommended configuration. If they need to customise theirs further they can do so.
Perhaps also submit the example to gitignore.io (https://www.toptal.com/developers/gitignore) to have it there too.

**Comment by VaclavElias** [comment]
Thank you for bringing up the importance of having a `.gitignore` file for this repo. We have just released a new doc version and this repo now contains this file.

Closing this issue as resolved.
