### ISSUE TITLE
How to add translation of docs on own language

### ISSUE THREAD

**Issue by snaulX** [stride3d/stride-docs#56]
I wanna start translate docs on Russian. How I can do it?

**Comment by VaclavElias** [comment]
This is being done in this PR https://github.com/stride3d/stride-docs/pull/88. 

This can be closed.

**Comment by VaclavElias** [comment]
Just a reference that a guide was created https://github.com/stride3d/stride-docs/blob/master/NewLanguageWorkflow.md
